{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "API BIBLIOTECA HORUS",
    "description": "Documentação das API's da Biblioteca Horus"
  },
  "host": "localhost:3000",
  "basePath": "",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/livro": {
      "get": {
        "tags": ["Livro"],
        "summary": "Endpoint para retornar os dados dos livros",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "post": {
        "tags": ["Livro"],
        "summary": "Endpoint para inserir os dados do livro",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/livro/{id}": {
      "delete": {
        "tags": ["Livro"],
        "summary": "Endpoint para excluir os dados de um determinado livro",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "patch": {
        "tags": ["Livro"],
        "summary": "Endpoint para atualizar dados especificos do livro",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "500": {
            "description": "Internal error"
          }
        }
      },
      "put": {
        "tags": ["Livro"],
        "summary": "Endpoint para atualizar todo os dados do livro",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/locacao": {
      "get": {
        "summary": "Endpoint para retornar os dados da locacao",
        "tags": ["Locacao"],
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "post": {
        "tags": ["Locacao"],
        "summary": "Endpoint para inserir os dados da locacao",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/locacao/{id}": {
      "delete": {
        "tags": ["Locacao"],
        "summary": "Endpoint para excluir os dados de um determinada locacao",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "patch": {
        "tags": ["Locacao"],
        "summary": "Endpoint para atualizar dados especificos do locacao",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "500": {
            "description": "Internal error"
          }
        }
      },
      "put": {
        "tags": ["Locacao"],
        "summary": "Endpoint para atualizar todo os dados da locacao",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/genero": {
      "get": {
        "summary": "Endpoint para retornar os dados do genero",
        "tags": ["Genero"],
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "post": {
        "tags": ["Genero"],
        "summary": "Endpoint para inserir os dados do genero",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/genero/{id}": {
      "delete": {
        "tags": ["Genero"],
        "summary": "Endpoint para excluir os dados de um determinado genero",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "patch": {
        "tags": ["Genero"],
        "summary": "Endpoint para atualizar dados especificos do genero",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "500": {
            "description": "Internal error"
          }
        }
      },
      "put": {
        "tags": ["Genero"],
        "summary": "Endpoint para atualizar todo os dados do genero",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/funcionario": {
      "get": {
        "tags": ["Funcionario"],
        "summary": "Endpoint para retornar os dados do funcionario",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "post": {
        "tags": ["Funcionario"],
        "summary": "Endpoint para inserir os dados do funcionario",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/funcionario/{id}": {
      "delete": {
        "tags": ["Funcionario"],
        "summary": "Endpoint para excluir os dados de um determinado funcionario",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "patch": {
        "tags": ["Funcionario"],
        "summary": "Endpoint para atualizar dados especificos do funcionario",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "500": {
            "description": "Internal error"
          }
        }
      },
      "put": {
        "tags": ["Funcionario"],
        "summary": "Endpoint para atualizar todo os dados do funcionario",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/estudante": {
      "get": {
        "tags": ["Estudante"],
        "summary": "Endpoint para retornar os dados do estudante",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "post": {
        "tags": ["Estudante"],
        "summary": "Endpoint para inserir os dados do estudante",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/estudante/{id}": {
      "delete": {
        "tags": ["Estudante"],
        "summary": "Endpoint para excluir os dados de um determinado estudante",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "patch": {
        "tags": ["Estudante"],
        "summary": "Endpoint para atualizar dados especificos do estudante",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "put": {
        "tags": ["Estudante"],
        "summary": "Endpoint para atualizar todo os dados do estudante",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucess!"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    }
  }
}